version: '3'
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  go_server:
    build:
      context: ./
    ports:
      - "8000:8000"
    depends_on:
      - postgres
volumes:
  postgres_data:
